package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("test hh vac")
    void generatedTest() {
        step("Open 'https://hh.ru/vacancy/55400128?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa'", () -> {
            step("// todo: just add selenium action");
        });

        step("Check header 'ООО Челлендж - Групп'", () -> {
            step("// todo: just add selenium action");
        });

        step("Check 'API'", () -> {
            step("// todo: just add selenium action");
        });

        step("Check 'HTTP, DOM, Git, Bash, CURL'", () -> {
            step("// todo: just add selenium action");
        });

        step("Check 'Jira, Confluence, BitBucket'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://hh.ru/vacancy/55400128?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa'", () ->
            open("https://hh.ru/vacancy/55400128?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa"));

        step("Page title should have text 'Вакансия QA Engineer (automation) в Москве, работа в компании Челлендж - Групп'", () -> {
            String expectedTitle = "Вакансия QA Engineer (automation) в Москве, работа в компании Челлендж - Групп";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://hh.ru/vacancy/55400128?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa'", () ->
            open("https://hh.ru/vacancy/55400128?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}